Feat/m1 mac support
joonatanaatos/3d-visualization pull request #1
Opened 2024-02-10 12:37 UTC by kahlstrm

- Add M1 mac support, previously the `build.sbt` didn't take into account CPU-architecture nor the special JVM flag `-XstartOnFirstThread` needed for GWT applications on Mac. 
- Updated shader code to be correct OpenGL 3.3 (wouldn't compile on my machine without these changes.
- Update sbt and scala version to enable Java 21 support
Tested this on Windows x86_64 and my M1 Macbook Pro, don't have a Linux with a DE around so can't test that unfortunately

2024-02-15 16:30 UTC, joonatanaatos requested changes

2024-02-15 16:30 UTC, joonatanaatos commented on README.md
> +1. Kloonaa projekti
Tää on itsestäänselvää

2024-02-15 16:30 UTC, joonatanaatos commented on README.md
> +Tarvittavat työkalut: Java SDK 21, sbt
Tän voisi laittaa bullet-pointeille

2024-02-15 16:30 UTC, joonatanaatos commented on src/main/resources/glsl/2d-color.frag
> +out vec4 fragColor;
Lisää rivinvaihto tähän

2024-02-15 16:30 UTC, joonatanaatos commented on src/main/resources/glsl/2d-texture.frag
> +out vec4 fragColor;
Lisää rivinvaihto tähän

2024-02-15 16:30 UTC, joonatanaatos commented on src/main/resources/glsl/3d-color.frag
> +out vec4 fragColor;
Lisää rivinvaihto tähän

2024-02-15 16:30 UTC, joonatanaatos commented on src/main/resources/glsl/3d-texture.frag
> +out vec4 fragColor;
Lisää rivinvaihto tähän

2024-02-15 21:46 UTC, kahlstrm commented on src/main/resources/glsl/2d-color.frag
> +out vec4 fragColor;
<img width="872" alt="image" src="https://github.com/joonatanaatos/3d-visualization/assets/71292737/d9d68f96-e196-4b04-a2e8-d5832338ade3">
Niin mihin?
Tossa on tollainen nappula, jolla voit esittää tässä sun kehottamat muutokset. Nyt en tiedä meinaatko rivinvaihtoa ennen vai jälkeen rivin.

2024-02-15 21:52 UTC, kahlstrm commented
Kuten sanottu, tämmöset pikku nitit kuten nää pilipali rivinvaihdot kannattaa käyttää tota `suggest change`-ominaisuutta. Sama pätee tohon Readme muutokseen, vitustako minä tiedän mitä toi tarkoittaa :D

2024-02-16 10:38 UTC, joonatanaatos approved these changes

2024-02-16 10:41 UTC, merged